module.exports = {
    angular: {
        files: [
            {expand: true, src: "**", cwd: 'node_modules/bootstrap/fonts',         dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'node_modules/font-awesome/fonts',      dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'node_modules/Simple-Line-Icons/fonts', dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/fonts',   dest: "angular/fonts"},
            {expand: true, src: "**", cwd: 'src/api',     dest: "angular/api"},
            {expand: true, src: "**", cwd: 'src/l10n',    dest: "angular/l10n"},
            {expand: true, src: "**", cwd: 'src/img',     dest: "angular/img"},
            {expand: true, src: "**", cwd: 'src/js',      dest: "angular/js"},
            {expand: true, src: "**", cwd: 'src/tpl',     dest: "angular/tpl"},
            {expand: true, src: "**", cwd: 'src/module',     dest: "angular/module"},
            {expand: true, src: "node_modules/easy-pie-chart/dist/jquery.easypiechart.js", dest: "angular"},
            {expand: true, src: "node_modules/jquery-sparkline/dist/jquery.sparkline.retina.js", dest: "angular"},
            {expand: true, src: "node_modules/flot/jquery.flot.js", dest: "angular"},
            {expand: true, src: "node_modules/flot/jquery.flot.pie.js", dest: "angular"},
            {expand: true, src: "node_modules/flot/jquery.flot.resize.js", dest: "angular"},
            {expand: true, src: "node_modules/flot.tooltip/js/jquery.flot.tooltip.js", dest: "angular"},
            {expand: true, src: "node_modules/flot.orderbars/js/jquery.flot.orderBars.js", dest: "angular"},
            {expand: true, src: "node_modules/flot-spline/js/jquery.flot.spline.js", dest: "angular"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "angular"},
            {expand: true, src: "node_modules/screenfull/dist/screenfull.min.js", dest: "angular"},
            {expand: true, src: "node_modules/slimscroll/jquery.slimscroll.min.js", dest: "angular"},
            {expand: true, src: "node_modules/html5sortable/jquery.sortable.js", dest: "angular"},
            {expand: true, src: "node_modules/nestable/jquery.nestable.js", dest: "angular"},
            {expand: true, src: "node_modules/nestable/jquery.nestable.css", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-filestyle/src/bootstrap-filestyle.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-slider/bootstrap-slider.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-slider/bootstrap-slider.css", dest: "angular"},
            {expand: true, src: "node_modules/chosen/chosen.jquery.min.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-chosen/bootstrap-chosen.css", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-wysiwyg/bootstrap-wysiwyg.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-wysiwyg/external/jquery.hotkeys.js", dest: "angular"},
            {expand: true, src: "node_modules/datatables/media/js/jquery.dataTables.min.js", dest: "angular"},
            {expand: true, src: "node_modules/datatables-bootstrap3-plugin/media/dataTables-bootstrap.js", dest: "angular"},
            {expand: true, src: "node_modules/datatables-bootstrap3-plugin/media/dataTables-bootstrap.css", dest: "angular"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-1.2.2.min.js", dest: "angular"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-world-mill-en.js", dest: "angular"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-us-aea-en.js", dest: "angular"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-1.2.2.css", dest: "angular"},
            {expand: true, src: "node_modules/footable/dist/footable.all.min.js", dest: "angular"},
            {expand: true, src: "node_modules/footable/css/footable.core.css", dest: "angular"},
            {expand: true, src: "node_modules/footable/css/fonts/footable.woff", dest: "angular"},
            {expand: true, src: "node_modules/footable/css/fonts/footable.ttf", dest: "angular"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "angular"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.min.js", dest: "angular"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.css", dest: "angular"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.theme.css", dest: "angular"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-daterangepicker/daterangepicker.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-daterangepicker/daterangepicker-bs3.css", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.js", dest: "angular"},
            {expand: true, src: "node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css", dest: "angular"},
            {expand: true, src: "node_modules/ng-grid/build/ng-grid.min.js", dest: "angular"},
            {expand: true, src: "node_modules/ng-grid/ng-grid.min.css", dest: "angular"},
            {expand: true, src: "node_modules/ng-grid/ng-grid.bootstrap.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.min.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.min.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.bootstrap.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-select/select.min.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-select/select.min.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-file-upload/angular-file-upload.min.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-ui-calendar/src/calendar.js", dest: "angular"},
            {expand: true, src: "node_modules/ng-img-crop/compile/minified/ng-img-crop.js", dest: "angular"},
            {expand: true, src: "node_modules/ng-img-crop/compile/minified/ng-img-crop.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-bootstrap-nav-tree/dist/abn_tree_directive.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-bootstrap-nav-tree/dist/abn_tree.css", dest: "angular"},
            {expand: true, src: "node_modules/angularjs-toaster/toaster.js", dest: "angular"},
            {expand: true, src: "node_modules/angularjs-toaster/toaster.css", dest: "angular"},
            {expand: true, src: "node_modules/textangular/dist/textangular-sanitize.min.js", dest: "angular"},
            {expand: true, src: "node_modules/textangular/dist/textangular.min.js", dest: "angular"},
            {expand: true, src: "node_modules/venturocket-angular-slider/build/angular-slider.min.js", dest: "angular"},
            {expand: true, src: "node_modules/venturocket-angular-slider/build/angular-slider.css", dest: "angular"},
            {expand: true, src: "node_modules/videogular/videogular.min.js", dest: "angular"},
            {expand: true, src: "node_modules/videogular-controls/controls.min.js", dest: "angular"},
            {expand: true, src: "node_modules/videogular-buffering/buffering.min.js", dest: "angular"},
            {expand: true, src: "node_modules/videogular-overlay-play/overlay-play.min.js", dest: "angular"},
            {expand: true, src: "node_modules/videogular-poster/poster.min.js", dest: "angular"},
            {expand: true, src: "node_modules/videogular-ima-ads/ima-ads.min.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-xeditable/dist/js/xeditable.min.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-xeditable/dist/css/xeditable.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-smart-table/dist/smart-table.min.js", dest: "angular"},
            {expand: true, src: "node_modules/ngmap/build/scripts/ng-map.min.js", dest: "angular"},
            {expand: true, src: "node_modules/ng-map-autocomplete/src/ng-map-autocomplete.js", dest: "angular"},
            {expand: true, src: "node_modules/angucomplete/angucomplete.css", dest: "angular"},
            {expand: true, src: "node_modules/angular-input-masks/releases/angular-input-masks-standalone.js", dest: "angular"},
            {expand: true, src: "node_modules/angular-input-masks/releases/angular-input-masks-dependencies.min.js", dest: "angular"},
            {expand: true, src: "node_modules/pdfmake/build/pdfmake.min.js", dest: "angular"},
            {expand: true, src: "pdf-font/vfs_fonts.js", dest: "angular/node_modules/pdfmake/build"},
            {src: 'src/index.min.html', dest : 'angular/index.html'}
        ]
    },
    html: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "html/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "html/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "html/fonts"},
            {expand: true, src: '**', cwd:'src/fonts/', dest: 'html/fonts/'},
            {expand: true, src: "**", cwd: 'src/api',     dest: "html/api"},
            {expand: true, src: '**', cwd:'src/img/', dest: 'html/img/'},
            {expand: true, src: '*.css', cwd:'src/css/', dest: 'html/css/'},
            {expand: true, src: '**', cwd:'swig/js/', dest: 'html/js/'}
        ]
    },
    landing: {
        files: [
            {expand: true, src: "**", cwd: 'bower_components/bootstrap/fonts',         dest: "landing/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/font-awesome/fonts',      dest: "landing/fonts"},
            {expand: true, src: "**", cwd: 'bower_components/Simple-Line-Icons/fonts', dest: "landing/fonts"},
            {expand: true, src:'**', cwd:'src/fonts/', dest: 'landing/fonts/'},
            {expand: true, src:'*.css', cwd:'src/css/', dest: 'landing/css/'},
            {src:'html/css/app.min.css', dest: 'landing/css/app.min.css'}
        ]
    },
    src: {
        files: [
            {expand: true, src: "node_modules/easy-pie-chart/dist/jquery.easypiechart.js", dest: "src"},
            {expand: true, src: "node_modules/jquery-sparkline/dist/jquery.sparkline.retina.js", dest: "src"},
            {expand: true, src: "node_modules/flot/jquery.flot.js", dest: "src"},
            {expand: true, src: "node_modules/flot/jquery.flot.pie.js", dest: "src"},
            {expand: true, src: "node_modules/flot/jquery.flot.resize.js", dest: "src"},
            {expand: true, src: "node_modules/flot.tooltip/js/jquery.flot.tooltip.js", dest: "src"},
            {expand: true, src: "node_modules/flot.orderbars/js/jquery.flot.orderBars.js", dest: "src"},
            {expand: true, src: "node_modules/flot-spline/js/jquery.flot.spline.js", dest: "src"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "src"},
            {expand: true, src: "node_modules/screenfull/dist/screenfull.min.js", dest: "src"},
            {expand: true, src: "node_modules/slimscroll/jquery.slimscroll.min.js", dest: "src"},
            {expand: true, src: "node_modules/html5sortable/jquery.sortable.js", dest: "src"},
            {expand: true, src: "node_modules/nestable/jquery.nestable.js", dest: "src"},
            {expand: true, src: "node_modules/nestable/jquery.nestable.css", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-filestyle/src/bootstrap-filestyle.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-slider/bootstrap-slider.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-slider/bootstrap-slider.css", dest: "src"},
            {expand: true, src: "node_modules/chosen/chosen.jquery.min.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-chosen/bootstrap-chosen.css", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-touchspin/dist/jquery.bootstrap-touchspin.min.css", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-wysiwyg/bootstrap-wysiwyg.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-wysiwyg/external/jquery.hotkeys.js", dest: "src"},
            {expand: true, src: "node_modules/datatables/media/js/jquery.dataTables.min.js", dest: "src"},
            {expand: true, src: "node_modules/datatables-bootstrap3-plugin/media/dataTables-bootstrap.js", dest: "src"},
            {expand: true, src: "node_modules/datatables-bootstrap3-plugin/media/dataTables-bootstrap.css", dest: "src"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-1.2.2.min.js", dest: "src"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-world-mill-en.js", dest: "src"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-us-aea-en.js", dest: "src"},
            {expand: true, src: "node_modules/bower-jvectormap/jquery-jvectormap-1.2.2.css", dest: "src"},
            {expand: true, src: "node_modules/footable/dist/footable.all.min.js", dest: "src"},
            {expand: true, src: "node_modules/footable/css/footable.core.css", dest: "src"},
            {expand: true, src: "node_modules/footable/css/fonts/footable.woff", dest: "src"},
            {expand: true, src: "node_modules/footable/css/fonts/footable.ttf", dest: "src"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "src"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.min.js", dest: "src"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.css", dest: "src"},
            {expand: true, src: "node_modules/fullcalendar/dist/fullcalendar.theme.css", dest: "src"},
            {expand: true, src: "node_modules/moment/moment.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-daterangepicker/daterangepicker.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-daterangepicker/daterangepicker-bs3.css", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.js", dest: "src"},
            {expand: true, src: "node_modules/bootstrap-tagsinput/dist/bootstrap-tagsinput.css", dest: "src"},
            {expand: true, src: "node_modules/ng-grid/build/ng-grid.min.js", dest: "src"},
            {expand: true, src: "node_modules/ng-grid/ng-grid.min.css", dest: "src"},
            {expand: true, src: "node_modules/ng-grid/ng-grid.bootstrap.css", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.min.js", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.min.css", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-grid/ui-grid.bootstrap.css", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-select/select.min.js", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-select/select.min.css", dest: "src"},
            {expand: true, src: "node_modules/angular-file-upload/angular-file-upload.min.js", dest: "src"},
            {expand: true, src: "node_modules/angular-ui-calendar/src/calendar.js", dest: "src"},
            {expand: true, src: "node_modules/ng-img-crop/compile/minified/ng-img-crop.js", dest: "src"},
            {expand: true, src: "node_modules/ng-img-crop/compile/minified/ng-img-crop.css", dest: "src"},
            {expand: true, src: "node_modules/angular-bootstrap-nav-tree/dist/abn_tree_directive.js", dest: "src"},
            {expand: true, src: "node_modules/angular-bootstrap-nav-tree/dist/abn_tree.css", dest: "src"},
            {expand: true, src: "node_modules/angularjs-toaster/toaster.js", dest: "src"},
            {expand: true, src: "node_modules/angularjs-toaster/toaster.css", dest: "src"},
            {expand: true, src: "node_modules/textangular/dist/textangular-sanitize.min.js", dest: "src"},
            {expand: true, src: "node_modules/textangular/dist/textangular.min.js", dest: "src"},
            {expand: true, src: "node_modules/venturocket-angular-slider/build/angular-slider.min.js", dest: "src"},
            {expand: true, src: "node_modules/venturocket-angular-slider/build/angular-slider.css", dest: "src"},
            {expand: true, src: "node_modules/videogular/videogular.min.js", dest: "src"},
            {expand: true, src: "node_modules/videogular-controls/controls.min.js", dest: "src"},
            {expand: true, src: "node_modules/videogular-buffering/buffering.min.js", dest: "src"},
            {expand: true, src: "node_modules/videogular-overlay-play/overlay-play.min.js", dest: "src"},
            {expand: true, src: "node_modules/videogular-poster/poster.min.js", dest: "src"},
            {expand: true, src: "node_modules/videogular-ima-ads/ima-ads.min.js", dest: "src"},
            {expand: true, src: "node_modules/angular-xeditable/dist/js/xeditable.min.js", dest: "src"},
            {expand: true, src: "node_modules/angular-xeditable/dist/css/xeditable.css", dest: "src"},
            {expand: true, src: "node_modules/angular-smart-table/dist/smart-table.min.js", dest: "src"},
            {expand: true, src: "node_modules/ngmap/build/scripts/ng-map.min.js", dest: "src"},
            {expand: true, src: "node_modules/ng-map-autocomplete/src/ng-map-autocomplete.js", dest: "src"},
            {expand: true, src: "node_modules/angucomplete/angucomplete.css", dest: "src"},
            {expand: true, src: "node_modules/angular-input-masks/releases/angular-input-masks-standalone.js", dest: "src"},
            {expand: true, src: "node_modules/angular-input-masks/releases/angular-input-masks-dependencies.min.js", dest: "src"},
            {expand: true, src: "node_modules/pdfmake/build/pdfmake.min.js", dest: "src"},
            {expand: true, src: "vfs_fonts.js", dest: "src/node_modules/pdfmake/build/"},
        ]
    },
    syno: {
        files: [
            {expand: true, src: "**", cwd: 'angular/', dest: "NVCorp/package/ui/app"}
        ]
    },
    synoindex: {
        files: [
            {src: "src/nvcorp.php", dest: "NVCorp/package/ui/app/nvcorp.php"},
            {src: "src/JWT.php", dest: "NVCorp/package/ui/app/JWT.php"},
        ]
    }
};
