'use strict';


angular.module('app', [
    'ngAnimate',
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ngTouch',
    'ngStorage',
    'ui.router',
    'ui.bootstrap',
    'ui.utils',
    'ui.load',
    'ui.jq',
    'oc.lazyLoad',
    'pascalprecht.translate',
    'btford.socket-io',
    // 'angularMoment',
    'angular.filter',
    'ui.grid',
    'ui.grid.autoResize',
    'ui.grid.edit',
    'ui.grid.selection',
    // 'ui.utils.masks',
    'angular-web-notification',
    // 'ngMap',
    // 'ngMapAutocomplete',
    'angucomplete-alt',
    // 'ui.dateTimeInput',
    "angular-table",
    // 'angular-loading-bar,'
    // 'monospaced.elastic',
    // 'weeklyScheduler',
    // 'weeklySchedulerI18N',
    // 'gantt',
    // 'gantt.sortable',
    // 'gantt.movable',
    // 'gantt.drawtask',
    // 'gantt.tooltips',
    // 'gantt.bounds',
    // 'gantt.progress',
    // 'gantt.table',
    // 'gantt.tree',
    // 'gantt.groups',
    // 'gantt.resizeSensor',
    // 'gantt.overlap',
    // 'gantt.dependencies',
    'ngMask'
]);